[project]
name = "flowmotion"
version = "0.1.0"
description = "A Manim-based animation library for visualizing data structures and algorithms."
authors = [{ name = "Mohammad Senan Ali" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "manim>=0.19.0"
]
